schema_version = "1.0.0"
id = "pymeshlab_integration"
version = "1.0.0"
name = "PyMeshLab Integration"
tagline = "Complete interface for supported PyMeshLab filters"
maintainer = "Arthur Zim"
type = "add-on"
blender_version_min = "5.2.0"
license = [
  "SPDX:GPL-3.0-or-later",
]
platforms = ["windows-x64"]

wheels = [
  "./wheels/pymeshlab-2025.7.post1-cp313-cp313-win_amd64.whl",
  "./wheels/msvc_runtime-14.44.35112-cp313-cp313-win_amd64.whl"
]

[permissions]
files = "Reads JSON configuration files to dynamically generate the filters UI"