import bpy
from bpy.types import PropertyGroup
from bpy.props import FloatProperty, BoolProperty
from ..base_filter import MeshLabFilterBase

# ==============================================================================
# Filtros relacionados a geração/reconstrução de malhas baseados na API do PyMeshLab.
# ==============================================================================


class MESHLAB_PG_generate_resampled_uniform_mesh(PropertyGroup, MeshLabFilterBase):
    pymeshlab_filter = "generate_resampled_uniform_mesh"
    requires_selection = True
    shade_flat = False
    remove_attributes = ["custom_normal", "sharp_edge", "sharp_face"]
    percentage_parameters = ["cellsize", "offset"]

    cellsize: FloatProperty(
        name="Precision",
        description="Size of the cell. Smaller cells give better precision at a higher computational cost. Remember that halving the cell size means that you build a volume 8 times larger.",
        subtype="DISTANCE",
        unit="LENGTH",
        default=0.03,
        min=0.0001,
        soft_min=0.01,
    )
    offset: FloatProperty(
        name="Offset",
        description="Offset of the created surface (i.e. distance of the created surface from the original one). If offset is zero, the created surface passes on the original mesh itself. Values greater than zero mean an external surface, and lower than zero mean an internal surface. In practice this value is the threshold passed to the Marching Cube algorithm to extract the isosurface from the distance field representation.",
        subtype="DISTANCE",
        unit="LENGTH",
        default=0.0,
        soft_min=-0.1,
        soft_max=1.0,
    )
    mergeclosevert: BoolProperty(
        name="Clean Vertices",
        description="If true the mesh generated by MC will be cleaned by unifying vertices that are almost coincident.",
        default=False,
    )
    discretize: BoolProperty(
        name="Discretize",
        description="If true the position of the intersected edge of the marching cube grid is not computed by linear interpolation, but it is placed in fixed middle position. As a consequence the resampled object will look severely aliased by a stairstep appearance. Useful only for simulating the output of 3D printing devices.",
        default=False,
    )
    multisample: BoolProperty(
        name="Multi-sample",
        description="If true the distance field is more accurately compute by multisampling the volume (7 sample for each voxel). Much slower but less artifacts.",
        default=False,
    )
    absdist: BoolProperty(
        name="Absolute Distance",
        description="If true a not signed distance field is computed. In this case you have to choose a not zero Offset and a double surface is built around the original surface, inside and outside. Is useful to convert thin floating surfaces into solid, thick meshes.",
        default=False,
    )
